### ISSUE TITLE
Firefox hanging

### ISSUE THREAD

**Issue by aspasch** [antoyo/auto-sort-bookmarks#29] opened 2016-07-18 16:51 UTC
Firefox (45.2.0) hanging just about few minuts of use. Turn it off and Firefox back to work.

**Comment by antoyo** [comment] 2016-07-18 16:55
There is currently no maintainer for this add-on.
I'm sorry, but if no one gets involved to support this add-on, it will soon (if it is not already the case) stop working.

**Comment by eric-bixby** [comment] 2016-07-18 19:24
I keep the auto feature turned off. Instead click on the add-on icon to
manually sort. Not as convenient but good enough.

**Comment by Gitoffthelawn** [comment] 2016-07-18 20:43
@antoyo Have you posted a "request for maintainer" on the AMO forum?

**Comment by eric-bixby** [comment] 2016-07-18 21:08
This issue is most likely a dup of issue #19.

I've seen a few people offer to take over, but I've seen zero contributions since @antoyo announced a "request for maintainer" last year.  Did they give up?

**Comment by antoyo** [comment] 2016-07-18 21:17
@Gitoffthelawn [Yes and no one answered.](https://discourse.mozilla-community.org/t/looking-for-someone-to-maintain-my-firefox-add-on/4029) I've also posted on some other forums without much success.
Moreover, one update of the add-on show a message to ask for a maintener.

@TheRealMarnes did some work on this add-on for some time. This is appreciated.

**Comment by eric-bixby** [comment] 2016-07-18 21:47
@antoyo. I'd hate to see this add-on go away.  I was going to offer before, but I thought you had someone.  I'm primarily a Java developer, but I have experience doing JavaScript also.

I realize everyone is different, but as a frame of reference, how much time do you allocate yourself on a daily/weekly basis for being the maintainer?

**Comment by TheRealMarnes** [comment] 2016-07-18 22:08
@antoyo thanks for the mention but tbh I don't recall doing anything noteworthy on it... I gave it up pretty quickly. Sorry.

**Comment by antoyo** [comment] 2016-07-18 22:55
@eric-bixby If you wish to only update the add-on so that it stays compatible with the new firefox releases, you will probably need a couple of hours per month (plus an initial time investment at the beginning to understand all the code and fix the issues like this one).

But if you wish to add new features and such, that will more likely be a few hours per week…
Or even more since I think a complete rewrite of the add-on would be beneficial, for instance to take advantage of e10s when it is good enough to sort the bookmarks concurrently (currently, the sorting "waits" from time to time so that it does not make Firefox freeze — though, apparently, it now does).

Thanks for your interest.

**Comment by Gitoffthelawn** [comment] 2016-07-19 04:13
@eric-bixby Although concurrent sorting would be beneficial, it's not a requirement, so I wouldn't let that get in your way.

Also, if you wanted to simplify things, you could have it work in manual mode only.

Basically, a working extension with fewer features is better than a non-working extension with all the bells and whistles.

**Comment by eric-bixby** [comment] 2016-07-19 04:43
The manual sort works fine, so the freeze is most likely caused by a
race-condition in the Thread class.  As @antoyo says, it's supposed to wait
so as to not lockup Firefox, but apparently that's broken with the newer
Firefox.

I agree disabling the auto-sort feature for now makes sense until a more
stable solution can be worked out.  Hopefully, people don't complain too
much that the Auto-sort is not auto.

**Comment by Gitoffthelawn** [comment] 2016-07-19 06:21
@eric-bixby If you choose to maintain the extension (or fork it), and remove the auto-sort, I think renaming it would be reasonable, so that such complaints could be avoided.

**Comment by antoyo** [comment] 2016-07-19 13:30
To fix this issue, someone could check, first of all, if there are errors in the error console.
Then, we could try setting a timeout with a value more than 0 [here](https://github.com/antoyo/auto-sort-bookmarks/blob/8ddfe2aafce9ee38851efe9ed71f959a62e2f8db/lib/thread.js#L35) to see if this fixes the issue (I think it was 100 in a previous version of the add-on). It will make the sorting slower, though.
Another idea would be to check if the bookmark observer behaves correctly (because I think it is the only code that runs in auto-sort and not in manual sort).
If nothing obvious is found out by these checks/updates, then we could easily disable the auto-sort option.

**Comment by eric-bixby** [comment] 2016-07-19 21:55
@Gitoffthelawn: I'd prefer to keep the product name as-is (for product recognition) and just send complaints to /dev/null.  Hopefully, disabling auto-sort will be temporary.  Also, the manual-sort not working, might just be in FF 45.X.  I noticed the icon looks disabled (possible color choice), regardless if that's the issue or not, I'd like to update the icon color and also have it change while a sort is in progress.

@antoyo: I'm planning to do my thread analysis this weekend when I have more time.  BTW, I'm doing my work in the following fork:
https://github.com/eric-bixby/auto-sort-bookmarks

**Comment by antoyo** [comment] 2016-07-20 23:12
@eric-bixby Do you wish to be added as a contributor on this GitHub project?

Also, I will need to add you as an author on AMO so that you can upload a new version.
To do so, you will need to send me the email address you used to register on AMO (you can send it to me by email if do you not wish to make it public).

Thanks for your work.

**Comment by antoyo** [comment] 2016-07-21 14:21
@eric-bixby I added you as a collaborator on GitHub and as an author on AMO.
I am not sure it worked on AMO though.
Could you please tell me if you received an invitation or something?

**Comment by eric-bixby** [comment] 2016-07-21 14:55
GitHub worked. However, I didn't receive any email for AMO.and it doesn't
list me on the website.

**Comment by antoyo** [comment] 2016-07-21 16:32
@eric-bixby I submitted a bug report on the AMO forum. I hope it will be fixed soon.

**Comment by eric-bixby** [comment] 2016-07-21 16:33
Yes, it works now. Thanks

**Comment by antoyo** [comment] 2016-07-22 20:36
One solution could be to revert back to version 2.7 ([as it seems to be less CPU intensive](https://github.com/antoyo/auto-sort-bookmarks/issues/19#issuecomment-137281338)) and apply only the fixes of the subsequent commits (not the new features) so that it works with the latest Firefox version (the add-on will lose some features though).

If you have any question, feel free to ask.

**Comment by eric-bixby** [comment] 2016-07-23 17:13
I tried the 2.7 version (just had to tweak the package.json to compile it).  It doesn't work as-is with the latest FF, so as you said, it would require patching.  However, that could be just as much work or more work than fixing the current code.  I feel confident that the problem with the current code is the threading.  I'm currently trying to figure out how to use the Firefox Profiler (lockups make this difficult).

**Comment by antoyo** [comment] 2016-07-23 18:18
Well, I'll let you manage this the way you want, but the version 2.7 was already fixed by the subsequent commits and this version used the `Thread` class as well, so this class may be good (or perhaps a new version of Firefox broke it, I don't know).
Anyway, thanks for your work.

**Comment by Gitoffthelawn** [comment] 2016-07-23 23:36
@eric-bixby Thanks for everything you are doing for this project!

**Comment by eric-bixby** [comment] 2016-07-24 16:12
My preliminary investigation is leaning toward an issue with the version of Firefox used.  I was not able to reproduce the high-load/freezing under FF 47.0.1.  While I did see it using FF 46.0.1.  I need to do more testing to determine which versions the issue is and isn't seen in.  Also, I'd like to know what the root cause is and find a workaround (other than upgrading Firefox).

**Comment by eric-bixby** [comment] 2016-08-17 03:27
This is a duplicate of issue #19.

Please see that issue for status updates.

**Closed by eric-bixby** 2016-08-17 03:27 UTC
Labels: bug, duplicate
