### ISSUE TITLE
Add back delay before sorting folders

### ISSUE THREAD

**Issue by michaelalandover** [antoyo/auto-sort-bookmarks#30] opened 2016-08-10 20:22 UTC
I use your bookmark sorting in conjunction with Xmarks to provide most recent clippings to my students, but now after adding it to new computer with v38 of Firefox, can't seem to get the sorting to do it in reverse order.  I don't see any way of changing any options except for whether or not to autosort.  I want reverse sort by date created.

**Comment by eric-bixby** [comment] 2016-08-11 03:28
If you select 'Tools' menu, select 'Add-ons', select 'Preferences' button
under 'Auto-Sort Bookmarks', then you should get a screen like the
following screenshot:

[image: Inline image 1]

Set the 'Sort by' and 'Inverse Order' checkbox to your preference.

**Comment by michaelalandover** [comment] 2016-08-11 15:11
Bingo on my windows 10 with version and latest firefox, thanks!  Send me link for a donation, thanks!
For some reason, on the university mandated version 38 of firefox at work, which doesn’t allow updates, those options aren’t showing!  The only option that shows is automatic or not and the further options just plain don’t show.

I have disabled the sorting at work, so bookmarks I add at work show up at the bottom of the list of bookmarks, even though they are the latest added.  When I open at home, it will import from xmarks the lastest list and sort it with latest at top and then update xmars, but that means a delay and times when my bookmarks aren’t sorted properly.

I’ve asked our tech support for permission to use later version of firefox.

Send me a link and I’ll make a contribution; great program!  I used sort places for a long time.

Absoilutely amazing firefox and other programs includilng the new EDGE don’t do this inside the brower.

It does seem to use a lot of memory; usualy firefox is under 300mb but somethings I see it up to 750 when I have your add on enabled.


mike

Michael A. Dover,M.S.S.W., Ph.D.
College Associate Lecturer
Editor, Reflections: Narratives of Professional Helping<http://www.rnoph.org/>
CSU Sponsor Representative, Cuyahoga County Conference on Social Welfare<http://www.naswoh.org/?page=cuyahogaconference>
School of Social Work, Cleveland State University
1425 Rhodes Tower
1860 E. 22nd St.
Cleveland OH 44115-2214
Office: (216)687-3564
Faculty profile<http://facultyprofile.csuohio.edu/csufacultyprofile/detail.cfm?FacultyID=M_A_DOVER> //LinkedIn profile<https://www.linkedin.com/in/michael-dover-1956914> //Human Needs: Overview<http://socialwork.oxfordre.com/view/10.1093/acrefore/9780199975839.001.0001/acrefore-9780199975839-e-554>
License: LISW (Ohio), LMSW (Clinical and Macro, Michigan)

**Comment by antoyo** [comment] 2016-08-11 15:26
@michaelalandover For your information, the version [2.10](https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/versions/2.10) _might_ work with Firefox 38.
If not, I am mostly sure that version [2.7.1](https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/versions/2.7.1-signed) will work (it has less features though).
If you downgrade the add-on, please check the settings because I don't think the option migration process works backward.

**Comment by eric-bixby** [comment] 2016-08-11 19:02
@michaelalandover I have a similar issue with my work computer.  We use an ESR version of Firefox that is locked down.  We are not able to install add-ons or change certain settings/preferences for IA/security reasons.  As @antoyo has stated, it's not a Firefox version issue.  Updating will not help you because the issue is likely a feature your IT/tech staff has disabled.

If you are experiencing high CPU/RAM usage, I'm still working on a possible fix.  As a workaround, leave the add-on enabled but disable auto sorting.  Uncheck the "Auto-Sort" option and then click on the Auto-Sort-Bookmarks icon in your toolbar to manually sort.

**Comment by michaelalandover** [comment] 2016-08-11 19:35
I have administrative rights so I installed V48; they just “don’t support” anything but v38.
It is working fine now.

I see now; the delay for folders is needed!  Nice tough, this explains why I keep having problems creating folders, it cuts me off in the middle of it due to a rapid sort no doubt!  Frankly, just a suggestion, I’d give it about a 10 second delay as default!

By the way, don’t know the meaning of the word “recursively”

At first I couldn’t find the Icon in the toolbar, but now I see it to the left of the 3 horizontal lines; it is a little seemingly greyed out.  But it works! Yay! As at work I have only 4 gigs of memory.  At home 32 gigs so I’ll leave it on there.

I wrote a very positive review, thanks much!

mike

Michael A. Dover,M.S.S.W., Ph.D.
College Associate Lecturer
Editor, Reflections: Narratives of Professional Helping<http://www.rnoph.org/>
CSU Sponsor Representative, Cuyahoga County Conference on Social Welfare<http://www.naswoh.org/?page=cuyahogaconference>
School of Social Work, Cleveland State University
1425 Rhodes Tower
1860 E. 22nd St.
Cleveland OH 44115-2214
Office: (216)687-3564
Faculty profile<http://facultyprofile.csuohio.edu/csufacultyprofile/detail.cfm?FacultyID=M_A_DOVER> //LinkedIn profile<https://www.linkedin.com/in/michael-dover-1956914> //Human Needs: Overview<http://socialwork.oxfordre.com/view/10.1093/acrefore/9780199975839.001.0001/acrefore-9780199975839-e-554>
License: LISW (Ohio), LMSW (Clinical and Macro, Michigan)

**Comment by antoyo** [comment] 2016-08-11 19:42
[The default folder delay is 30 seconds.](https://github.com/antoyo/auto-sort-bookmarks/blob/master/package.json#L30)
Perhaps you this value was updated somehow.

**Comment by eric-bixby** [comment] 2016-11-26 18:31
Closing: Adding back delay preference will be address in #41

**Closed by eric-bixby** 2016-11-26 18:31 UTC
Labels: Priority: Medium, Status: Pending, Type: Enhancement
